"""Tests for asset-serving and css-styling examples."""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

from jac_client.plugin.vite_client_bundle import ViteClientBundleBuilder
from jaclang.pycore.runtime import JacRuntime as Jac


@pytest.fixture(autouse=True)
def reset_jac_machine():
    """Reset Jac machine before and after each test."""
    Jac.reset_machine()
    yield
    Jac.reset_machine()


def _create_test_project_with_vite(
    temp_path: Path, include_assets: bool = False
) -> tuple[Path, Path]:
    """Create a minimal test project with Vite installed using config.json.

    Args:
        temp_path: Path to the temporary directory
        include_assets: If True, includes asset handling setup
    """
    # Create config.json with package dependencies
    # Note: React, React-DOM, React-Router-DOM, Vite, and Babel packages
    # are automatically added during build time, so we only include custom packages
    config_data = {
        "vite": {
            "plugins": [],
            "lib_imports": [],
            "build": {
                "minify": False,
            },
            "server": {},
            "resolve": {},
        },
        "ts": {},
        "package": {
            "name": "test-client",
            "version": "0.0.1",
            "description": "Test client project",
            "dependencies": {},
            "devDependencies": {},
        },
    }

    config_json = temp_path / "config.json"
    with config_json.open("w", encoding="utf-8") as f:
        json.dump(config_data, f, indent=2)

    # Install packages from config.json using jac add --cl
    # This generates package.json in .jac-client.configs/ and runs npm install
    # Note: vite.config.js is now auto-generated by the build system
    # The system automatically includes @jac-client/assets alias when needed
    result = subprocess.run(
        ["jac", "add", "--cl"],
        cwd=temp_path,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        error_msg = f"jac add --cl failed with exit code {result.returncode}\n"
        error_msg += f"stdout: {result.stdout}\n"
        error_msg += f"stderr: {result.stderr}\n"
        raise RuntimeError(error_msg)

    # Package.json is generated in .jac-client.configs/ directory
    package_json = temp_path / ".jac-client.configs" / "package.json"
    if not package_json.exists():
        raise RuntimeError(
            f"package.json not generated at {package_json}. "
            "jac add --cl should have created it."
        )

    # Create output directory
    output_dir = temp_path / "dist"
    output_dir.mkdir(parents=True, exist_ok=True)

    compiled_dir = temp_path / "compiled"
    compiled_dir.mkdir(parents=True, exist_ok=True)

    build_dir = temp_path / "build"
    build_dir.mkdir(parents=True, exist_ok=True)

    return package_json, output_dir


def test_image_asset_example() -> None:
    """Test image-asset example with static asset paths."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)

        package_json, output_dir = _create_test_project_with_vite(
            temp_path, include_assets=True
        )
        runtime_path = Path(__file__).parent.parent / "plugin" / "client_runtime.cl.jac"

        # Initialize the Vite builder
        builder = ViteClientBundleBuilder(
            runtime_path=runtime_path,
            vite_package_json=package_json,
            vite_output_dir=output_dir,
            vite_minify=False,
        )

        # Import the image-asset example
        examples_dir = (
            Path(__file__).parent.parent / "examples" / "asset-serving" / "image-asset"
        )
        (module,) = Jac.jac_import("app", str(examples_dir))

        # Build the bundle
        bundle = builder.build(module, force=True)

        # Verify bundle structure
        assert bundle is not None
        assert bundle.module_name == "app"
        assert "app" in bundle.client_functions

        # Verify image path is in the bundle
        assert "/static/assets/burger.png" in bundle.code

        # Verify bundle was written to output directory
        bundle_files = list(output_dir.glob("client.*.js"))
        assert len(bundle_files) > 0, "Expected at least one bundle file"

        # Cleanup
        builder.cleanup_temp_dir()


def test_css_with_image_example() -> None:
    """Test css-with-image example with CSS and image assets."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)

        package_json, output_dir = _create_test_project_with_vite(
            temp_path, include_assets=True
        )
        runtime_path = Path(__file__).parent.parent / "plugin" / "client_runtime.cl.jac"

        # Initialize the Vite builder
        builder = ViteClientBundleBuilder(
            runtime_path=runtime_path,
            vite_package_json=package_json,
            vite_output_dir=output_dir,
            vite_minify=False,
        )

        # Import the css-with-image example
        examples_dir = (
            Path(__file__).parent.parent
            / "examples"
            / "asset-serving"
            / "css-with-image"
        )
        (module,) = Jac.jac_import("app", str(examples_dir))

        # Build the bundle
        bundle = builder.build(module, force=True)

        # Verify bundle structure
        assert bundle is not None
        assert bundle.module_name == "app"
        assert "app" in bundle.client_functions

        # Verify CSS import is present (CSS should be extracted to separate file)
        # The bundle should reference the CSS file
        assert "import" in bundle.code.lower()

        # Verify image paths are in the bundle
        assert "/static/assets/burger.png" in bundle.code

        # Verify CSS file was extracted
        css_files = list(output_dir.glob("*.css"))
        assert len(css_files) > 0, "Expected at least one CSS file"

        # Verify bundle was written to output directory
        bundle_files = list(output_dir.glob("client.*.js"))
        assert len(bundle_files) > 0, "Expected at least one bundle file"

        # Cleanup
        builder.cleanup_temp_dir()


def test_import_alias_example() -> None:
    """Test import-alias example with @jac-client/assets alias."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        package_json, output_dir = _create_test_project_with_vite(
            temp_path, include_assets=True
        )
        runtime_path = Path(__file__).parent.parent / "plugin" / "client_runtime.cl.jac"

        # Initialize the Vite builder
        builder = ViteClientBundleBuilder(
            runtime_path=runtime_path,
            vite_package_json=package_json,
            vite_output_dir=output_dir,
            vite_minify=False,
        )

        # Import the import-alias example
        examples_dir = (
            Path(__file__).parent.parent / "examples" / "asset-serving" / "import-alias"
        )
        (module,) = Jac.jac_import("app", str(examples_dir))

        # Copy assets from example directory to temp project's compiled/assets/
        # This is needed because @jac-client/assets alias points to compiled/assets
        example_assets_dir = examples_dir / "assets"
        temp_assets_dir = temp_path / "compiled" / "assets"
        if example_assets_dir.exists():
            temp_assets_dir.mkdir(parents=True, exist_ok=True)
            # Copy all files from example assets to temp assets
            for asset_file in example_assets_dir.iterdir():
                if asset_file.is_file():
                    shutil.copy2(asset_file, temp_assets_dir / asset_file.name)

        # Build the bundle
        bundle = builder.build(module, force=True)

        # Verify bundle structure
        assert bundle is not None
        assert bundle.module_name == "app"
        assert "app" in bundle.client_functions

        # Verify the import alias was processed by Vite
        # Vite should have resolved the asset import
        # The bundle should contain the processed asset URL
        # assert "burgerImage" in bundle.code

        # Verify bundle was written to output directory
        bundle_files = list(output_dir.glob("client.*.js"))
        assert len(bundle_files) > 0, "Expected at least one bundle file"

        # Cleanup
        builder.cleanup_temp_dir()
